modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/superlord9362/WorldOfWonder"
license="LGPL v3"

[[mods]]
modId="worldofwonder"
version = "${file.jarVersion}"
itemIcon = "just_dandy:fluffy_dandelion"
configBackground = "worldofwonder:textures/block/dandelion_fluff.png"
displayName="World of Wonder"
credits="Ms. Random (Code), Coda (Art), Cosmos (Ideas, Code), Kenzie (Code), Mr. Esuoh (Sounds), superlord9362 (Code)"
description='''
World of Wonder is a mod that was made for MMD's ModJam. It contains a new biome, the Dandelion Fields.
'''
logoFile = "logo.png"
displayURL = "https://modrinth.com/project/world-of-wonder"

[[dependencies.worldofwonder]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.worldofwonder]]
modId = "forge"
mandatory = true
versionRange = "[47.2,)"
ordering = "NONE"
side = "BOTH"
    